### ISSUE TITLE
Empty Nake.csx fails to run with 3.0.0-beta-02 due to NuGet resolution errors

### ISSUE THREAD

**Issue by alexrp** [yevhen/Nake#38]
I created an empty `Nake.csx` just to give Nake a try. Attempting to run `dotnet tool run nake` (version `3.0.0-beta-01`) gives:

```
Unable to restore packages from 'C:\Users\alex\AppData\Local\Temp\scripts\C\Users\alex\source\repos\tests\netcoreapp3.1\script.csproj'. Make sure that all script files contains valid NuGet references
```

The contents of that file are:

```xml
﻿<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup></ItemGroup>
  <Target Name="RecordReferencePaths" AfterTargets="AfterResolveReferences">
    <WriteLinesToFile File="$(OutputPath)/ReferencePaths.txt" Lines="@(ReferencePath)" />
  </Target>
</Project>
```

Running with `--trace` gives:

```
Creating project file for *.csx files found in C:\Users\alex\source\repos\tests using netcoreapp3.1 as the default framework.
Parsing C:\Users\alex\source\repos\tests\Nake.csx
Project file saved to C:\Users\alex\AppData\Local\Temp\scripts\C\Users\alex\source\repos\tests\netcoreapp3.1\script.csproj
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup></ItemGroup>
  <Target Name="RecordReferencePaths" AfterTargets="AfterResolveReferences">
    <WriteLinesToFile File="$(OutputPath)/ReferencePaths.txt" Lines="@(ReferencePath)" />
  </Target>
</Project>
Computing compilation dependencies
Creating project file for *.csx files found in C:\Users\alex\source\repos\tests using netcoreapp3.1 as the default framework.
Parsing C:\Users\alex\source\repos\tests\Nake.csx
Project file saved to C:\Users\alex\AppData\Local\Temp\scripts\C\Users\alex\source\repos\tests\netcoreapp3.1\script.csproj
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup></ItemGroup>
  <Target Name="RecordReferencePaths" AfterTargets="AfterResolveReferences">
    <WriteLinesToFile File="$(OutputPath)/ReferencePaths.txt" Lines="@(ReferencePath)" />
  </Target>
</Project>
Restoring C:\Users\alex\AppData\Local\Temp\scripts\C\Users\alex\source\repos\tests\netcoreapp3.1\script.csproj using the dotnet cli. RuntimeIdentifier : win10-x64 NugetConfigFile: C:\Users\alex\source\repos\tests\NuGet.Config
Executing 'dotnet restore "C:\Users\alex\AppData\Local\Temp\scripts\C\Users\alex\source\repos\tests\netcoreapp3.1\script.csproj" -r win10-x64  --configfile "C:\Users\alex\source\repos\tests\NuGet.Config"'
  Determining projects to restore...
C:\Users\alex\AppData\Local\Temp\scripts\C\Users\alex\source\repos\tests\netcoreapp3.1\script.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Runtime.win-x64 (= 3.1.7)' for '.NETCoreApp,Version=v3.1'.
C:\Users\alex\AppData\Local\Temp\scripts\C\Users\alex\source\repos\tests\netcoreapp3.1\script.csproj : error NU1100: Unable to resolve 'Microsoft.WindowsDesktop.App.Runtime.win-x64 (= 3.1.7)' for '.NETCoreApp,Version=v3.1'.
C:\Users\alex\AppData\Local\Temp\scripts\C\Users\alex\source\repos\tests\netcoreapp3.1\script.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.App.Runtime.win-x64 (= 3.1.7)' for '.NETCoreApp,Version=v3.1'.
  Failed to restore C:\Users\alex\AppData\Local\Temp\scripts\C\Users\alex\source\repos\tests\netcoreapp3.1\script.csproj (in 148 ms).
Unable to restore packages from 'C:\Users\alex\AppData\Local\Temp\scripts\C\Users\alex\source\repos\tests\netcoreapp3.1\script.csproj'. Make sure that all script files contains valid NuGet references
   at Dotnet.Script.DependencyModel.Context.DotnetRestorer.Restore(ProjectFileInfo projectFileInfo, String[] packageSources)
   at Dotnet.Script.DependencyModel.Context.ProfiledRestorer.Restore(ProjectFileInfo projectFileInfo, String[] packageSources)
   at Dotnet.Script.DependencyModel.Compilation.CompilationDependencyResolver.GetDependencies(String targetDirectory, IEnumerable`1 scriptFiles, Boolean enableScriptNugetReferences, String defaultTargetFramework)
   at Nake.Scripting.Script.CompilationDependencies(ScriptSource source) in C:\Work\OSS\Nake\Source\Nake\Scripting\Script.cs:line 108
   at Nake.Scripting.Script.Compile(ScriptSource source, AssemblyReference[] dependencies) in C:\Work\OSS\Nake\Source\Nake\Scripting\Script.cs:line 70
   at Nake.BuildEngine.Compile(ScriptSource source, AssemblyReference[] dependencies) in C:\Work\OSS\Nake\Source\Nake\Build.cs:line 68
   at Nake.BuildEngine.Build(BuildInput input) in C:\Work\OSS\Nake\Source\Nake\Build.cs:line 54
   at Nake.CachingBuildEngine.Build(BuildInput input) in C:\Work\OSS\Nake\Source\Nake\Caching.cs:line 59
   at Nake.Application.Build(ScriptSource source, IEnumerable`1 declarations) in C:\Work\OSS\Nake\Source\Nake\Application.cs:line 105
   at Nake.Application.Invoke(ScriptSource source, IEnumerable`1 declarations)
   at Nake.Application.Start() in C:\Work\OSS\Nake\Source\Nake\Application.cs:line 54
   at Nake.Program.StartApplication(String[] args) in C:\Work\OSS\Nake\Source\Nake\Program.cs:line 55
   at Nake.Program.Main(String[] args) in C:\Work\OSS\Nake\Source\Nake\Program.cs:line 19
   at Nake.Program.<Main>(String[] args)
```

... which isn't terribly helpful either, as far as I can tell.

In case it matters, my `dotnet --info` is:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 5.0.0-preview.7.20364.11
  Commit:  53976d38b1

.NET SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I wonder if there's some kind of issue caused by the fact that I'm using .NET 5? I wouldn't *think* so since tools are supposed to run with the .NET Core version they're built for, and I do have .NET Core 3 installed as well...

**Comment by alexrp** [comment]
```console
$ dotnet nake --version
3.0.0-beta-02
```

**Comment by yevhen** [comment]
Ok, I’ll check what’s wrong and come back soon

**Comment by yevhen** [comment]
Sorry for such a long delay((
I haven't figured out what the cause was.
Nake 3.0 for net5 and 3.2 for net7 are already out, so you may try these versions if you're still interested :)
